import { MaintenanceService } from '../services/maintenance/maintenance.service';
import assert from 'node:assert/strict';
import { PrismaClient } from '@prisma/client';
import { AllocationEngine } from '../services/allocation/allocation.service';
import { FulfillmentService } from '../services/fulfillment/fulfillment.service';
import { DispatchService } from '../services/fulfillment/dispatch.service';
import { OtpService } from '../services/otp/otp.service';
import { PrivacyMasker } from '../middleware/privacy';
import { hashPassword, verifyPassword } from '../services/auth/auth.service';
import { server, io } from '../app';
import { prisma as appPrisma } from '../lib/prisma';
import { io as clientIO } from 'socket.io-client';

const prisma = new PrismaClient();
const engine = new AllocationEngine(prisma);
const fulfillment = new FulfillmentService(prisma);
const sockets: ReturnType<typeof clientIO>[] = [];
async function main() {
  assert.match(process.env.DATABASE_URL || '', /\/tmp\/.+test/); // Never touch the project database.
  const donor = await prisma.user.create({ data: { name: 'Donor', email: 'donor@test.local', role: 'DONOR', donorProfile: { create: { organizationName: 'Kitchen', donorType: 'RESTAURANT', address: 'Private pickup', latitude: 40.71, longitude: -74, phone: 'PRIVATE-PHONE' } } }, include: { donorProfile: true } });
  const receiver = await prisma.user.create({ data: { name: 'Receiver', email: 'receiver@test.local', role: 'RECEIVER', receiverProfile: { create: { organizationName: 'Shelter', maxCapacity: 20, foodPreferences: '["COOKED_MEALS"]', needLevel: 'HIGH', address: 'Private destination', latitude: 40.711, longitude: -74, phone: 'PRIVATE-PHONE', hasOwnLogistics: true } } }, include: { receiverProfile: true } });
  const makeDriver = (email: string) => prisma.user.create({ data: { name: email, email, role: 'DRIVER', driverProfile: { create: { fullName: email, vehicleType: 'BIKE', phone: 'PRIVATE-PHONE', currentLatitude: 40.71, currentLongitude: -74 } } }, include: { driverProfile: true } });
  const [driver, other] = await Promise.all([makeDriver('driver@test.local'), makeDriver('other@test.local')]);
  const donation = (quantity: number) => prisma.donation.create({ data: { donorId: donor.donorProfile!.id, foodCategory: 'COOKED_MEALS', foodDescription: 'Meals', quantity, pickupAddress: 'Private pickup', pickupLatitude: 40.71, pickupLongitude: -74, availableAt: new Date(Date.now()-1000), safeDeadline: new Date(Date.now()+3600000) } });
  const [a,b] = await Promise.all([donation(15), donation(15)]);
  await Promise.all([engine.proposeAllocationsForDonation(a.id), engine.proposeAllocationsForDonation(b.id)]);
  const capacity = await prisma.receiverProfile.findUniqueOrThrow({ where: { id: receiver.receiverProfile!.id } });
  assert.equal(capacity.reservedIncomingQuantity,20);
  assert.equal((await prisma.donationAllocation.aggregate({ _sum: { allocatedQuantity: true } }))._sum.allocatedQuantity,20);
  await assert.rejects(prisma.receiverProfile.update({ where: { id: capacity.id }, data: { reservedIncomingQuantity: 30 } }));
  console.log('PASS concurrent capacity reservation and database capacity constraint');
  const allocations = await prisma.donationAllocation.findMany({ orderBy: { allocatedQuantity: 'desc' } });
  const allocation = allocations[0];
  await Promise.all([engine.proposeAllocationsForDonation(allocation.donationId), engine.proposeAllocationsForDonation(allocation.donationId)]);
  assert.equal(await prisma.donationAllocation.count({ where: { donationId: allocation.donationId } }),1);
  const accepts = await Promise.allSettled([engine.acceptAllocation(allocation.id),engine.acceptAllocation(allocation.id)]);
  assert.equal(accepts.filter(r=>r.status==='fulfilled').length,1);
  const delivery = await fulfillment.createDeliveryForAllocation(allocation.id, 'PLATFORM_DRIVER', undefined, receiver.id);
  assert.match(delivery.pickupOtp,/^v1\./);
  assert.equal(JSON.stringify(PrivacyMasker.maskDeliveryForUser(delivery, driver as any)).includes('pickupOtp'),false);
  await assert.rejects(engine.rejectAllocation(allocation.id));
  await assert.rejects(fulfillment.cancelPlatformDriver(delivery.id,other.driverProfile!.id,'not mine'));
  await assert.rejects(fulfillment.verifyPickupOtp(delivery.id,'123456',other.id));
  const dispatch = new DispatchService(prisma,200);
  const claims = await Promise.allSettled([
    dispatch.claim(delivery.id,other.driverProfile!.id,{latitude:40.74,longitude:-74}),
    dispatch.claim(delivery.id,driver.driverProfile!.id,{latitude:40.71,longitude:-74}),
  ]);
  assert.equal(claims.filter(r=>r.status==='fulfilled').length,1);
  const assignment = await prisma.driverAssignment.findFirstOrThrow({ where: { deliveryId: delivery.id, status: 'ACCEPTED' } });
  assert.equal(assignment.driverId,driver.driverProfile!.id);
  console.log('PASS lowest-ETA claim window, one winner, ownership and invalid-transition rejection');
  const pickup = OtpService.reveal(delivery.pickupOtp,`${allocation.id}:PICKUP`);
  const receipt = OtpService.reveal(delivery.deliveryOtp,`${allocation.id}:DELIVERY`);
  await assert.rejects(fulfillment.verifyPickupOtp(delivery.id,pickup === '111111' ? '222222' : '111111',driver.id));
  assert.equal(await prisma.oTPVerification.count({ where: { deliveryId: delivery.id, isSuccessful: false } }),1);
  assert.equal((await prisma.oTPVerification.findFirstOrThrow()).submittedOtp,'[REDACTED]');
  await fulfillment.verifyPickupOtp(delivery.id,pickup,driver.id);
  await assert.rejects(fulfillment.cancelPlatformDriver(delivery.id,driver.driverProfile!.id,'after pickup'));
  await assert.rejects(fulfillment.switchDeliveryMode(delivery.id,'RECEIVER_LOGISTICS',{driverName:'Staff'},receiver.id));
  const finishes = await Promise.allSettled([fulfillment.verifyDeliveryOtp(delivery.id,receipt,driver.id),fulfillment.verifyDeliveryOtp(delivery.id,receipt,driver.id)]);
  assert.equal(finishes.filter(r=>r.status==='fulfilled').length,1);
  assert.equal(await prisma.impactRecord.count({ where: { deliveryId: delivery.id } }),1);
  assert.equal((await prisma.donation.findUniqueOrThrow({where:{id:allocation.donationId}})).status,'FULFILLED');
  assert.equal((await prisma.driverProfile.findUniqueOrThrow({where:{id:driver.driverProfile!.id}})).isAvailable,true);
  await assert.rejects(fulfillment.cancelPlatformDriver(delivery.id,driver.driverProfile!.id,'completed'));
  console.log('PASS encrypted OTPs, committed failed-attempt audit, replay rejection, one impact, driver release');
  // Second allocation: reject twice concurrently, capacity released exactly once and historical rejects excluded.
  const rejectResults = await Promise.allSettled([engine.rejectAllocation(allocations[1].id),engine.rejectAllocation(allocations[1].id)]);
  assert.equal(rejectResults.filter(r=>r.status==='fulfilled').length,1);
  assert.equal((await prisma.receiverProfile.findUniqueOrThrow({where:{id:capacity.id}})).reservedIncomingQuantity,0);
  await prisma.receiverProfile.update({where:{id:capacity.id},data:{maxCapacity:100}});
  const c = await donation(10);
  const proposed = await engine.proposeAllocationsForDonation(c.id);
  await engine.acceptAllocation(proposed.allocations[0].id);
  const own = await fulfillment.createDeliveryForAllocation(proposed.allocations[0].id,'RECEIVER_LOGISTICS',{driverName:'Staff'},receiver.id);
  await fulfillment.switchDeliveryMode(own.id,'PLATFORM_DRIVER',undefined,receiver.id);
  await fulfillment.acceptPlatformDeliveryJob(own.id,driver.driverProfile!.id,{latitude:40.71,longitude:-74});
  await fulfillment.switchDeliveryMode(own.id,'RECEIVER_LOGISTICS',{driverName:'New Staff'},receiver.id);
  assert.equal(await prisma.driverAssignment.count({where:{deliveryId:own.id,status:'ACCEPTED'}}),0);
  const ownCode=OtpService.reveal(own.pickupOtp,`${own.allocationId}:PICKUP`);
  for(let n=0;n<5;n++) await assert.rejects(fulfillment.verifyPickupOtp(own.id,ownCode==='111111'?'222222':'111111',receiver.id));
  await assert.rejects(fulfillment.verifyPickupOtp(own.id,ownCode,receiver.id),/Too many/);
  assert.equal(await prisma.oTPVerification.count({where:{deliveryId:own.id,isSuccessful:false}}),5);
  assert.throws(()=>OtpService.reveal(OtpService.seal('123456','expired',new Date(Date.now()-1)),'expired'));
  assert.throws(()=>OtpService.reveal(delivery.deliveryOtp,`${allocation.id}:PICKUP`));
  await prisma.donation.update({ where: { id: c.id }, data: { safeDeadline: new Date(Date.now()-1000) } });
  const expiry = new MaintenanceService(prisma);
  await Promise.all([expiry.expireDonation(c.id), expiry.expireDonation(c.id)]);
  assert.equal((await prisma.receiverProfile.findUniqueOrThrow({ where: { id: capacity.id } })).reservedIncomingQuantity,0);
  assert.equal((await prisma.delivery.findUniqueOrThrow({ where: { id: own.id } })).status,'EXPIRED');
  assert.equal(await prisma.impactRecord.count(),1);
  console.log('PASS concurrent expiry releases capacity once without impact');
  console.log('PASS rejection race, mode-switch assignment cleanup, own logistics, OTP lockout/expiry/stage binding');
  // HTTP and sockets: anonymous, role, object access and actual password sessions.
  const password='test-password-at-least-twelve';
  await prisma.user.update({where:{id:driver.id},data:{passwordHash:await hashPassword(password)}});
  assert.equal(await verifyPassword('wrong',await hashPassword(password)),false);
  await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));
  const address=server.address() as {port:number}; const base=`http://127.0.0.1:${address.port}`;
  const request=(path:string,user?:string,body?:unknown)=>fetch(`${base}/api${path}`,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(user?{'x-user-id':user}:{})},...(body?{body:JSON.stringify(body)}:{})});
  const summary = await (await request('/impact/summary',donor.id)).json() as any;
  assert.equal(summary.totalMealsRescued,allocation.allocatedQuantity);
  assert.equal(summary.categoryBreakdown.COOKED_MEALS.meals,allocation.allocatedQuantity);
  assert.equal(typeof summary.categoryBreakdown.COOKED_MEALS.meals,'number');
  const pageOne = await request('/donations/my?limit=1',donor.id);
  assert.equal((await pageOne.json() as any[]).length,1);
  const cursor = pageOne.headers.get('X-Next-Cursor'); assert.ok(cursor);
  const pageTwo = await request(`/donations/my?limit=1&cursor=${cursor}`,donor.id);
  const nextRows = await pageTwo.json() as any[]; assert.notEqual(nextRows[0].id,cursor);
  assert.equal((await request('/donations/my?limit=10000',donor.id)).status,400);
  assert.equal((await request('/admin/dashboard')).status,401);
  assert.equal((await request('/admin/dashboard',driver.id)).status,403);
  assert.equal((await request(`/deliveries/${own.id}`,other.id)).status,404);
  assert.equal((await request(`/deliveries/${own.id}/verify-pickup-otp`,other.id,{otp:ownCode})).status,404);
  assert.equal((await request('/donations',donor.id,{foodCategory:'COOKED_MEALS',foodDescription:'test',quantity:1.2,safeDeadline:new Date(Date.now()+3600000).toISOString()})).status,400);
  const directory=await (await request('/auth/users')).json() as any[];
  assert.equal(directory.some(u=>u.passwordHash || u.email || u.receiverProfile),false);
  const ownData=await (await request(`/deliveries/${own.id}`,receiver.id)).json();
  assert.equal(/pickupOtp|deliveryOtp|PRIVATE-PHONE/.test(JSON.stringify(ownData)),false);
  const login=await request('/auth/login',undefined,{email:driver.email,password});
  assert.equal(login.status,200);
  const cookie=login.headers.get('set-cookie')!.split(';')[0];
  assert.match(login.headers.get('set-cookie')!,/HttpOnly/);
  const me=await (await fetch(`${base}/api/auth/me`,{headers:{cookie}})).json() as any;
  assert.equal(me.id,driver.id); assert.equal('passwordHash' in me,false);
  const socket=clientIO(base,{auth:{userId:driver.id},transports:['websocket'],reconnection:false}); sockets.push(socket);
  await new Promise<void>((resolve,reject)=>{socket.once('connect',resolve);socket.once('connect_error',reject);});
  socket.emit('join:role','ADMIN');socket.emit('join:user',receiver.id);socket.emit('join:delivery',own.id);
  await new Promise(resolve=>setTimeout(resolve,100));
  const rooms=io.sockets.sockets.get(socket.id!)!.rooms;
  assert.equal(rooms.has('role:ADMIN'),false);assert.equal(rooms.has(`user:${receiver.id}`),false);assert.equal(rooms.has(`delivery:${own.id}`),false);
  const anonymous=clientIO(base,{transports:['websocket'],reconnection:false}); sockets.push(anonymous);
  await new Promise<void>((resolve,reject)=>{anonymous.once('connect',()=>reject(new Error('Anonymous socket accepted')));anonymous.once('connect_error',()=>resolve());});
  console.log('PASS HTTP authorization/privacy/validation, session login, authenticated socket room isolation');
}
main().catch(err=>{console.error(err);process.exitCode=1;}).finally(async()=>{for(const socket of sockets)socket.disconnect();io.close();server.close();await prisma.$disconnect();await appPrisma.$disconnect();});
